ACACIA_DOOR = "ACACIA_DOOR"
ACACIA_DOOR_ITEM = "ACACIA_DOOR_ITEM"
ACACIA_FENCE = "ACACIA_FENCE"
ACACIA_FENCE_GATE = "ACACIA_FENCE_GATE"
ACACIA_STAIRS = "ACACIA_STAIRS"
ACTIVATOR_RAIL = "ACTIVATOR_RAIL"
AIR = "AIR"
ANVIL = "ANVIL"
APPLE = "APPLE"
ARMOR_STAND = "ARMOR_STAND"
ARROW = "ARROW"
BAKED_POTATO = "BAKED_POTATO"
BANNER = "BANNER"
BARRIER = "BARRIER"
BEACON = "BEACON"
BED = "BED"
BED_BLOCK = "BED_BLOCK"
BEDROCK = "BEDROCK"
BIRCH_DOOR = "BIRCH_DOOR"
BIRCH_DOOR_ITEM = "BIRCH_DOOR_ITEM"
BIRCH_FENCE = "BIRCH_FENCE"
BIRCH_FENCE_GATE = "BIRCH_FENCE_GATE"
BIRCH_WOOD_STAIRS = "BIRCH_WOOD_STAIRS"
BLAZE_POWDER = "BLAZE_POWDER"
BLAZE_ROD = "BLAZE_ROD"
BOAT = "BOAT"
BONE = "BONE"
BOOK = "BOOK"
BOOK_AND_QUILL = "BOOK_AND_QUILL"
BOOKSHELF = "BOOKSHELF"
BOW = "BOW"
BOWL = "BOWL"
BREAD = "BREAD"
BREWING_STAND = "BREWING_STAND"
BREWING_STAND_ITEM = "BREWING_STAND_ITEM"
BRICK = "BRICK"
BRICK_STAIRS = "BRICK_STAIRS"
BROWN_MUSHROOM = "BROWN_MUSHROOM"
BUCKET = "BUCKET"
BURNING_FURNACE = "BURNING_FURNACE"
CACTUS = "CACTUS"
CAKE = "CAKE"
CAKE_BLOCK = "CAKE_BLOCK"
CARPET = "CARPET"
CARROT = "CARROT"
CARROT_ITEM = "CARROT_ITEM"
CARROT_STICK = "CARROT_STICK"
CAULDRON = "CAULDRON"
CAULDRON_ITEM = "CAULDRON_ITEM"
CHAINMAIL_BOOTS = "CHAINMAIL_BOOTS"
CHAINMAIL_CHESTPLATE = "CHAINMAIL_CHESTPLATE"
CHAINMAIL_HELMET = "CHAINMAIL_HELMET"
CHAINMAIL_LEGGINGS = "CHAINMAIL_LEGGINGS"
CHEST = "CHEST"
CLAY = "CLAY"
CLAY_BALL = "CLAY_BALL"
CLAY_BRICK = "CLAY_BRICK"
COAL = "COAL"
COAL_BLOCK = "COAL_BLOCK"
COAL_ORE = "COAL_ORE"
COBBLE_WALL = "COBBLE_WALL"
COBBLESTONE = "COBBLESTONE"
COBBLESTONE_STAIRS = "COBBLESTONE_STAIRS"
COCOA = "COCOA"
COMMAND = "COMMAND"
COMMAND_MINECART = "COMMAND_MINECART"
COMPASS = "COMPASS"
COOKED_BEEF = "COOKED_BEEF"
COOKED_CHICKEN = "COOKED_CHICKEN"
COOKED_FISH = "COOKED_FISH"
COOKED_MUTTON = "COOKED_MUTTON"
COOKED_RABBIT = "COOKED_RABBIT"
COOKIE = "COOKIE"
CROPS = "CROPS"
DARK_OAK_DOOR = "DARK_OAK_DOOR"
DARK_OAK_DOOR_ITEM = "DARK_OAK_DOOR_ITEM"
DARK_OAK_FENCE = "DARK_OAK_FENCE"
DARK_OAK_FENCE_GATE = "DARK_OAK_FENCE_GATE"
DARK_OAK_STAIRS = "DARK_OAK_STAIRS"
DAYLIGHT_DETECTOR = "DAYLIGHT_DETECTOR"
DAYLIGHT_DETECTOR_INVERTED = "DAYLIGHT_DETECTOR_INVERTED"
DEAD_BUSH = "DEAD_BUSH"
DETECTOR_RAIL = "DETECTOR_RAIL"
DIAMOND = "DIAMOND"
DIAMOND_AXE = "DIAMOND_AXE"
DIAMOND_BARDING = "DIAMOND_BARDING"
DIAMOND_BLOCK = "DIAMOND_BLOCK"
DIAMOND_BOOTS = "DIAMOND_BOOTS"
DIAMOND_CHESTPLATE = "DIAMOND_CHESTPLATE"
DIAMOND_HELMET = "DIAMOND_HELMET"
DIAMOND_HOE = "DIAMOND_HOE"
DIAMOND_LEGGINGS = "DIAMOND_LEGGINGS"
DIAMOND_ORE = "DIAMOND_ORE"
DIAMOND_PICKAXE = "DIAMOND_PICKAXE"
DIAMOND_SPADE = "DIAMOND_SPADE"
DIAMOND_SWORD = "DIAMOND_SWORD"
DIODE = "DIODE"
DIODE_BLOCK_OFF = "DIODE_BLOCK_OFF"
DIODE_BLOCK_ON = "DIODE_BLOCK_ON"
DIRT = "DIRT"
DISPENSER = "DISPENSER"
DOUBLE_PLANT = "DOUBLE_PLANT"
DOUBLE_STEP = "DOUBLE_STEP"
DOUBLE_STONE_SLAB2 = "DOUBLE_STONE_SLAB2"
DRAGON_EGG = "DRAGON_EGG"
DROPPER = "DROPPER"
EGG = "EGG"
EMERALD = "EMERALD"
EMERALD_BLOCK = "EMERALD_BLOCK"
EMERALD_ORE = "EMERALD_ORE"
EMPTY_MAP = "EMPTY_MAP"
ENCHANTED_BOOK = "ENCHANTED_BOOK"
ENCHANTMENT_TABLE = "ENCHANTMENT_TABLE"
ENDER_CHEST = "ENDER_CHEST"
ENDER_PEARL = "ENDER_PEARL"
ENDER_PORTAL = "ENDER_PORTAL"
ENDER_PORTAL_FRAME = "ENDER_PORTAL_FRAME"
ENDER_STONE = "ENDER_STONE"
EXP_BOTTLE = "EXP_BOTTLE"
EXPLOSIVE_MINECART = "EXPLOSIVE_MINECART"
EYE_OF_ENDER = "EYE_OF_ENDER"
FEATHER = "FEATHER"
FENCE = "FENCE"
FENCE_GATE = "FENCE_GATE"
FERMENTED_SPIDER_EYE = "FERMENTED_SPIDER_EYE"
FIRE = "FIRE"
FIREBALL = "FIREBALL"
FIREWORK = "FIREWORK"
FIREWORK_CHARGE = "FIREWORK_CHARGE"
FISHING_ROD = "FISHING_ROD"
FLINT = "FLINT"
FLINT_AND_STEEL = "FLINT_AND_STEEL"
FLOWER_POT = "FLOWER_POT"
FLOWER_POT_ITEM = "FLOWER_POT_ITEM"
FURNACE = "FURNACE"
GHAST_TEAR = "GHAST_TEAR"
GLASS = "GLASS"
GLASS_BOTTLE = "GLASS_BOTTLE"
GLOWING_REDSTONE_ORE = "GLOWING_REDSTONE_ORE"
GLOWSTONE = "GLOWSTONE"
GLOWSTONE_DUST = "GLOWSTONE_DUST"
GOLD_AXE = "GOLD_AXE"
GOLD_BARDING = "GOLD_BARDING"
GOLD_BLOCK = "GOLD_BLOCK"
GOLD_BOOTS = "GOLD_BOOTS"
GOLD_CHESTPLATE = "GOLD_CHESTPLATE"
GOLD_HELMET = "GOLD_HELMET"
GOLD_HOE = "GOLD_HOE"
GOLD_INGOT = "GOLD_INGOT"
GOLD_LEGGINGS = "GOLD_LEGGINGS"
GOLD_NUGGET = "GOLD_NUGGET"
GOLD_ORE = "GOLD_ORE"
GOLD_PICKAXE = "GOLD_PICKAXE"
GOLD_PLATE = "GOLD_PLATE"
GOLD_RECORD = "GOLD_RECORD"
GOLD_SPADE = "GOLD_SPADE"
GOLD_SWORD = "GOLD_SWORD"
GOLDEN_APPLE = "GOLDEN_APPLE"
GOLDEN_CARROT = "GOLDEN_CARROT"
GRASS = "GRASS"
GRAVEL = "GRAVEL"
GREEN_RECORD = "GREEN_RECORD"
GRILLED_PORK = "GRILLED_PORK"
HARD_CLAY = "HARD_CLAY"
HAY_BLOCK = "HAY_BLOCK"
HOPPER = "HOPPER"
HOPPER_MINECART = "HOPPER_MINECART"
HUGE_MUSHROOM_1 = "HUGE_MUSHROOM_1"
HUGE_MUSHROOM_2 = "HUGE_MUSHROOM_2"
ICE = "ICE"
INK_SACK = "INK_SACK"
IRON_AXE = "IRON_AXE"
IRON_BARDING = "IRON_BARDING"
IRON_BLOCK = "IRON_BLOCK"
IRON_BOOTS = "IRON_BOOTS"
IRON_CHESTPLATE = "IRON_CHESTPLATE"
IRON_DOOR = "IRON_DOOR"
IRON_DOOR_BLOCK = "IRON_DOOR_BLOCK"
IRON_FENCE = "IRON_FENCE"
IRON_HELMET = "IRON_HELMET"
IRON_HOE = "IRON_HOE"
IRON_INGOT = "IRON_INGOT"
IRON_LEGGINGS = "IRON_LEGGINGS"
IRON_ORE = "IRON_ORE"
IRON_PICKAXE = "IRON_PICKAXE"
IRON_PLATE = "IRON_PLATE"
IRON_SPADE = "IRON_SPADE"
IRON_SWORD = "IRON_SWORD"
IRON_TRAPDOOR = "IRON_TRAPDOOR"
ITEM_FRAME = "ITEM_FRAME"
JACK_O_LANTERN = "JACK_O_LANTERN"
JUKEBOX = "JUKEBOX"
JUNGLE_DOOR = "JUNGLE_DOOR"
JUNGLE_DOOR_ITEM = "JUNGLE_DOOR_ITEM"
JUNGLE_FENCE = "JUNGLE_FENCE"
JUNGLE_FENCE_GATE = "JUNGLE_FENCE_GATE"
JUNGLE_WOOD_STAIRS = "JUNGLE_WOOD_STAIRS"
LADDER = "LADDER"
LAPIS_BLOCK = "LAPIS_BLOCK"
LAPIS_ORE = "LAPIS_ORE"
LAVA = "LAVA"
LAVA_BUCKET = "LAVA_BUCKET"
LEASH = "LEASH"
LEATHER = "LEATHER"
LEATHER_BOOTS = "LEATHER_BOOTS"
LEATHER_CHESTPLATE = "LEATHER_CHESTPLATE"
LEATHER_HELMET = "LEATHER_HELMET"
LEATHER_LEGGINGS = "LEATHER_LEGGINGS"
LEAVES = "LEAVES"
LEAVES_2 = "LEAVES_2"
LEVER = "LEVER"
LOG = "LOG"
LOG_2 = "LOG_2"
LONG_GRASS = "LONG_GRASS"
MAGMA_CREAM = "MAGMA_CREAM"
MAP = "MAP"
MELON = "MELON"
MELON_BLOCK = "MELON_BLOCK"
MELON_SEEDS = "MELON_SEEDS"
MELON_STEM = "MELON_STEM"
MILK_BUCKET = "MILK_BUCKET"
MINECART = "MINECART"
MOB_SPAWNER = "MOB_SPAWNER"
MONSTER_EGG = "MONSTER_EGG"
MONSTER_EGGS = "MONSTER_EGGS"
MOSSY_COBBLESTONE = "MOSSY_COBBLESTONE"
MUSHROOM_SOUP = "MUSHROOM_SOUP"
MUTTON = "MUTTON"
MYCEL = "MYCEL"
NAME_TAG = "NAME_TAG"
NETHER_BRICK = "NETHER_BRICK"
NETHER_BRICK_ITEM = "NETHER_BRICK_ITEM"
NETHER_BRICK_STAIRS = "NETHER_BRICK_STAIRS"
NETHER_FENCE = "NETHER_FENCE"
NETHER_STALK = "NETHER_STALK"
NETHER_STAR = "NETHER_STAR"
NETHER_WARTS = "NETHER_WARTS"
NETHERRACK = "NETHERRACK"
NOTE_BLOCK = "NOTE_BLOCK"
OBSIDIAN = "OBSIDIAN"
PACKED_ICE = "PACKED_ICE"
PAINTING = "PAINTING"
PAPER = "PAPER"
PISTON_BASE = "PISTON_BASE"
PISTON_EXTENSION = "PISTON_EXTENSION"
PISTON_MOVING_PIECE = "PISTON_MOVING_PIECE"
PISTON_STICKY_BASE = "PISTON_STICKY_BASE"
POISONOUS_POTATO = "POISONOUS_POTATO"
PORK = "PORK"
PORTAL = "PORTAL"
POTATO = "POTATO"
POTATO_ITEM = "POTATO_ITEM"
POTION = "POTION"
POWERED_MINECART = "POWERED_MINECART"
POWERED_RAIL = "POWERED_RAIL"
PRISMARINE = "PRISMARINE"
PRISMARINE_CRYSTALS = "PRISMARINE_CRYSTALS"
PRISMARINE_SHARD = "PRISMARINE_SHARD"
PUMPKIN = "PUMPKIN"
PUMPKIN_PIE = "PUMPKIN_PIE"
PUMPKIN_SEEDS = "PUMPKIN_SEEDS"
PUMPKIN_STEM = "PUMPKIN_STEM"
QUARTZ = "QUARTZ"
QUARTZ_BLOCK = "QUARTZ_BLOCK"
QUARTZ_ORE = "QUARTZ_ORE"
QUARTZ_STAIRS = "QUARTZ_STAIRS"
RABBIT = "RABBIT"
RABBIT_FOOT = "RABBIT_FOOT"
RABBIT_HIDE = "RABBIT_HIDE"
RABBIT_STEW = "RABBIT_STEW"
RAILS = "RAILS"
RAW_BEEF = "RAW_BEEF"
RAW_CHICKEN = "RAW_CHICKEN"
RAW_FISH = "RAW_FISH"
RECORD_10 = "RECORD_10"
RECORD_11 = "RECORD_11"
RECORD_12 = "RECORD_12"
RECORD_3 = "RECORD_3"
RECORD_4 = "RECORD_4"
RECORD_5 = "RECORD_5"
RECORD_6 = "RECORD_6"
RECORD_7 = "RECORD_7"
RECORD_8 = "RECORD_8"
RECORD_9 = "RECORD_9"
RED_MUSHROOM = "RED_MUSHROOM"
RED_ROSE = "RED_ROSE"
RED_SANDSTONE = "RED_SANDSTONE"
RED_SANDSTONE_STAIRS = "RED_SANDSTONE_STAIRS"
REDSTONE = "REDSTONE"
REDSTONE_BLOCK = "REDSTONE_BLOCK"
REDSTONE_COMPARATOR = "REDSTONE_COMPARATOR"
REDSTONE_COMPARATOR_OFF = "REDSTONE_COMPARATOR_OFF"
REDSTONE_COMPARATOR_ON = "REDSTONE_COMPARATOR_ON"
REDSTONE_LAMP_OFF = "REDSTONE_LAMP_OFF"
REDSTONE_LAMP_ON = "REDSTONE_LAMP_ON"
REDSTONE_ORE = "REDSTONE_ORE"
REDSTONE_TORCH_OFF = "REDSTONE_TORCH_OFF"
REDSTONE_TORCH_ON = "REDSTONE_TORCH_ON"
REDSTONE_WIRE = "REDSTONE_WIRE"
ROTTEN_FLESH = "ROTTEN_FLESH"
SADDLE = "SADDLE"
SAND = "SAND"
SANDSTONE = "SANDSTONE"
SANDSTONE_STAIRS = "SANDSTONE_STAIRS"
SAPLING = "SAPLING"
SEA_LANTERN = "SEA_LANTERN"
SEEDS = "SEEDS"
SHEARS = "SHEARS"
SIGN = "SIGN"
SIGN_POST = "SIGN_POST"
SKULL = "SKULL"
SKULL_ITEM = "SKULL_ITEM"
SLIME_BALL = "SLIME_BALL"
SLIME_BLOCK = "SLIME_BLOCK"
SMOOTH_BRICK = "SMOOTH_BRICK"
SMOOTH_STAIRS = "SMOOTH_STAIRS"
SNOW = "SNOW"
SNOW_BALL = "SNOW_BALL"
SNOW_BLOCK = "SNOW_BLOCK"
SOIL = "SOIL"
SOUL_SAND = "SOUL_SAND"
SPECKLED_MELON = "SPECKLED_MELON"
SPIDER_EYE = "SPIDER_EYE"
SPONGE = "SPONGE"
SPRUCE_DOOR = "SPRUCE_DOOR"
SPRUCE_DOOR_ITEM = "SPRUCE_DOOR_ITEM"
SPRUCE_FENCE = "SPRUCE_FENCE"
SPRUCE_FENCE_GATE = "SPRUCE_FENCE_GATE"
SPRUCE_WOOD_STAIRS = "SPRUCE_WOOD_STAIRS"
STAINED_CLAY = "STAINED_CLAY"
STAINED_GLASS = "STAINED_GLASS"
STAINED_GLASS_PANE = "STAINED_GLASS_PANE"
STANDING_BANNER = "STANDING_BANNER"
STATIONARY_LAVA = "STATIONARY_LAVA"
STATIONARY_WATER = "STATIONARY_WATER"
STEP = "STEP"
STICK = "STICK"
STONE = "STONE"
STONE_AXE = "STONE_AXE"
STONE_BUTTON = "STONE_BUTTON"
STONE_HOE = "STONE_HOE"
STONE_PICKAXE = "STONE_PICKAXE"
STONE_PLATE = "STONE_PLATE"
STONE_SLAB2 = "STONE_SLAB2"
STONE_SPADE = "STONE_SPADE"
STONE_SWORD = "STONE_SWORD"
STORAGE_MINECART = "STORAGE_MINECART"
STRING = "STRING"
SUGAR = "SUGAR"
SUGAR_CANE = "SUGAR_CANE"
SUGAR_CANE_BLOCK = "SUGAR_CANE_BLOCK"
SULPHUR = "SULPHUR"
THIN_GLASS = "THIN_GLASS"
TNT = "TNT"
TORCH = "TORCH"
TRAP_DOOR = "TRAP_DOOR"
TRAPPED_CHEST = "TRAPPED_CHEST"
TRIPWIRE = "TRIPWIRE"
TRIPWIRE_HOOK = "TRIPWIRE_HOOK"
VINE = "VINE"
WALL_BANNER = "WALL_BANNER"
WALL_SIGN = "WALL_SIGN"
WATCH = "WATCH"
WATER = "WATER"
WATER_BUCKET = "WATER_BUCKET"
WATER_LILY = "WATER_LILY"
WEB = "WEB"
WHEAT = "WHEAT"
WOOD = "WOOD"
WOOD_AXE = "WOOD_AXE"
WOOD_BUTTON = "WOOD_BUTTON"
WOOD_DOOR = "WOOD_DOOR"
WOOD_DOUBLE_STEP = "WOOD_DOUBLE_STEP"
WOOD_HOE = "WOOD_HOE"
WOOD_PICKAXE = "WOOD_PICKAXE"
WOOD_PLATE = "WOOD_PLATE"
WOOD_SPADE = "WOOD_SPADE"
WOOD_STAIRS = "WOOD_STAIRS"
WOOD_STEP = "WOOD_STEP"
WOOD_SWORD = "WOOD_SWORD"
WOODEN_DOOR = "WOODEN_DOOR"
WOOL = "WOOL"
WORKBENCH = "WORKBENCH"
WRITTEN_BOOK = "WRITTEN_BOOK"
YELLOW_FLOWER = "YELLOW_FLOWER"

resu_str = """panels:\n"""
resu_dict = """panels:\n"""

dt = "&5&lSmelting Recipe&0&l>> &r"

dd = [
    {
        "title": "S:Baked Potato",
        "1": {"m": POTATO, "id": "", "link": "C:"},
        "res": {"m": BAKED_POTATO, "id": ""}
    },
    {
        "title": "S:Cooked Chicken",
        "1": {"m": RAW_CHICKEN, "id": "", "link": "C:"},
        "res": {"m": COOKED_CHICKEN, "id": ""}
    },
    {
        "title": "S:Cooked Fish",
        "1": {"m": RAW_FISH, "id": "", "link": "C:"},
        "res": {"m": COOKED_FISH, "id": ""}
    },
    {
        "title": "S:Cooked Porkchop",
        "1": {"m": PORK, "id": "", "link": "C:"},
        "res": {"m": GRILLED_PORK, "id": ""}
    },
    {
        "title": "S:Steak",
        "1": {"m": RAW_BEEF, "id": "", "link": "C:"},
        "res": {"m": COOKED_BEEF, "id": ""}
    },
    {
        "title": "S:Brick",
        "1": {"m": CLAY_BALL, "id": "", "link": "C:"},
        "res": {"m": CLAY_BRICK, "id": ""}
    },
    {
        "title": "S:Glass",
        "1": {"m": SAND, "id": "", "link": "C:"},
        "res": {"m": GLASS, "id": ""}
    },
    {
        "title": "S:Gold Ingot",
        "1": {"m": GOLD_ORE, "id": "", "link": "G:Ore"},
        "res": {"m": GOLD_INGOT, "id": ""}
    },
    {
        "title": "S:Hardened Clay",
        "1": {"m": CLAY, "id": "", "link": "C:ClayBlock"},
        "res": {"m": HARD_CLAY, "id": ""}
    },
    {
        "title": "S:Iron Ingot",
        "1": {"m": IRON_ORE, "id": "", "link": "G:Ore"},
        "res": {"m": IRON_INGOT, "id": ""}
    },
    {
        "title": "S:Nether Brick",
        "1": {"m": NETHERRACK, "id": "", "link": "C:Netherrack"},
        "res": {"m": NETHER_BRICK_ITEM, "id": ""}
    },
    {
        "title": "S:Stone",
        "1": {"m": COBBLESTONE, "id": "", "link": "G:Cobblestone"},
        "res": {"m": STONE, "id": ""}
    },
    {
        "title": "S:GreenDye",
        "1": {"m": CACTUS, "id": "", "link": "C:"},
        "res": {"m": INK_SACK, "id": "2"}
    },
    {
        "title": "S:Charcoal",
        "1": {"m": LOG, "id": "", "link": "C:"},
        "res": {"m": COAL, "id": "1"}
    },
    {
        "title": "S:Coal",
        "1": {"m": COAL_ORE, "id": "", "link": "G:Ore"},
        "res": {"m": COAL, "id": ""}
    },
    {
        "title": "S:Diamond",
        "1": {"m": DIAMOND_ORE, "id": "", "link": "G:Ore"},
        "res": {"m": DIAMOND, "id": ""}
    },
    {
        "title": "S:Emerald",
        "1": {"m": EMERALD_ORE, "id": "", "link": "G:Ore"},
        "res": {"m": EMERALD, "id": ""}
    },
    {
        "title": "S:Lapis Lazuli",
        "1": {"m": LAPIS_ORE, "id": "", "link": "G:Ore"},
        "res": {"m": INK_SACK, "id": "4"}
    },
    {
        "title": "S:Quartz",
        "1": {"m": QUARTZ_ORE, "id": "", "link": "G:Ore"},
        "res": {"m": QUARTZ, "id": ""}
    },
    {
        "title": "S:Redstone",
        "1": {"m": REDSTONE_ORE, "id": "", "link": "G:Ore"},
        "res": {"m": REDSTONE_ORE, "id": ""}
    },
]

for i in dd:
    temp_yml = """"""
    temp_dict_yml = """"""

    title = i["title"]

    name = ""
    for titleSplit in title.split():
        name += titleSplit

    temp_1 = i["1"]
    temp_1_id = ""
    temp_1_link = ""
    temp_1_m = ""

    temp_res = i["res"]
    temp_res_m = temp_res["m"]
    temp_res_id = ""

    if(temp_res["m"] == ""):
        temp_res_m = AIR
    else:
        temp_res_m = temp_res["m"]
    if(temp_res["id"] == ""):
        temp_res_id = "0"
    else:
        temp_res_id = temp_res["id"]

    if(temp_1["m"] == ""):
        temp_1_m = AIR
    else:
        temp_1_m = temp_1["m"]
    if(temp_1["id"] == ""):
        temp_1_id = "0"
    else:
        temp_1_id = temp_1["id"]
    if(temp_1["link"] != "C:"):
        temp_1_link =f"""commands:\n          - open= {temp_1["link"]}\n        lore:\n          - '&eClick to view recipe'\n"""

    temp_yml = f"""  {name}:\n    title: '{dt}{title}'\n    empty: STAINED_GLASS_PANE\n    emptyID: '15'\n    rows: '3'\n    item:\n      '10':\n        material: '{temp_1_m}'\n        ID: '{temp_1_id}'\n        {temp_1_link}\n      '12':\n        material: '{FURNACE}'\n        name: 'To'\n        ID: '0'\n      '14':\n        material: '{temp_res_m}'\n        ID: '{temp_res_id}'\n      "26":\n        material: 'FEATHER'\n        name: '&e&lBack'\n        commands:\n          - open= item-guide-book-1\n      "17":\n        material: 'BARRIER'\n        name: "&c&lClose"\n        commands:\n          - cpc"""
    temp_dict_yml = f"""
    \n      '':
    \n        name: '{title}'
    \n        material: '{temp_res_m}'
    \n        ID: '{temp_res_id}'
    \n        lore:
    \n          - '&eClick for more details.'
    \n        commands:
    \n          - open= {name}
    """
    resu_str += temp_yml + "\n\n\n"
    resu_dict += temp_dict_yml + "\n"

f = open("smelting-recipe.yml", "wt")
fd = open("smelting-recipe-book.yml", "wt")
f.write(resu_str)
fd.write(resu_dict)